name: ttyd
adopt-info: ttyd
summary: Share your terminal over the web
description: |
 ttyd is a simple command-line tool for sharing terminal over the web

grade: stable
confinement: classic
base: core20
compression: lzo

license: MIT

assumes:
  - command-chain

apps:
  ttyd:
    command: usr/bin/ttyd
    command-chain: 
      - bin/homeishome-launch       

parts:
  ttyd:
    source: https://github.com/tsl0922/ttyd
    source-type: git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-environment:
      - LDFLAGS: "-pthread"
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - build-essential 
      - libjson-c-dev 
      - libwebsockets-dev
      
    stage-packages:
      - build-essential 
      - libjson-c-dev 
      - libwebsockets-dev
      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch  
