main.plugins.educational-purposes-only-exclusively.enabled = false
main.plugins.educational-purposes-only-exclusively.home-password = "Sp1d3rM@n"
main.plugins.educational-purposes-only-exclusively.home_network = "B33zH1v3!"
main.plugins.educational-purposes-only-exclusively.minimum-signal-strength = -75
