main.plugins.fancygotchi.bg = true
main.plugins.fancygotchi.bg_image = "ui-bg-w.png" # <-- this one for "lcdhat", and "ui-bg-w-s.png" for the "waveshare144lcd"
main.plugins.fancygotchi.enabled = true
main.plugins.fancygotchi.hi-res = true
main.plugins.fancygotchi.theme = ""
main.plugins.fancygotchi.themes_path = ""
