main.plugins.led-ng.led = PWR
main.plugins.led-ng.delay = 200
main.plugins.led-ng.enabled = true
main.plugins.led-ng.patterns.ai_best_reward = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.ai_ready = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.ai_training_start = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.ai_worst_reward = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.association = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.bored = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.deauthentication = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.epoch = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.excited = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.handshake = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.loaded = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.lonely = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.peer_detected = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.peer_lost = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.ready = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.rebooting = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.sad = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.sleep = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.unread_inbox = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.updating = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.wait = "oo  oo  oo oo  oo  oo  oo"
main.plugins.led-ng.patterns.wifi_update = "oo  oo  oo oo  oo  oo  oo"
